#!/bin/sh
module="kbdscan"
device="kbdscan"
mode="664"

search="\$2==\"$module\" {print \$1}"
echo $search

# invoke insmod with all parameters we got
/sbin/insmod ./$module.ko $* || exit 1

# remove stale nodes
rm -f /dev/${device}

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

mknod /dev/${device} c $major 0

# give appropriate group/permissions, and change the group
# Not all distributions have "staff", some have "wheel" instead
group="staff"
grep -q '^staff:' /etc/group || group="wheel"

chgrp $group /dev/${device}
chmod $mode  /dev/${device}

